output_root: '/content/drive/My Drive/STEGO_results/eval/'
pytorch_data_dir: '/content/drive/My Drive/STEGO_dataset/'
experiment_name: "sentinel2"
res: 224
batch_size: 1
num_workers: 1
run_picie: True
run_crf: False # True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  - "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
